### ISSUE TITLE
username_1 vs username1

### ISSUE THREAD

**Issue by bogenschlag** [leifos-gmbh/AutoGenerateUsername#1]
Hi Fabian, thanks for fixing the include path last week. I had spoken with Stefan about the plugin and he told me we could also get rid of the _ that plugin right now inserts into username before the numbers (ig. "ChristianBogen" would become "ChristianBogen_1", but wee *need* "ChristianBogen1"—we can’t modify our naming schema after all these years). Can you tackle this before tomorrow? Thanks!

**Comment by fwolf-ilias** [comment]
Hi, 
the changes are commited. This was one of my TODO's for today.

Have fun using this Plugin.

**Comment by bogenschlag** [comment]
Awesome, thank you! 😃👍🏼
