### ISSUE TITLE
Minor username nitpicking 

### ISSUE THREAD

**Issue by bogenschlag** [leifos-gmbh/AutoGenerateUsername#2]
I just stress-tested the plugin with really mean imaginary name: Ärnö Sçhmí∂t. Now it came out alright, but *could* sill be a bit better: AErnoeSchmit. ;) The the »∂« got lost completely is no big deal, we probably won’t get many Icelandic guest students anyway. (I guess, »œ« would be lost, too?) But the »Ä« of course should become »Ae«, not »AE«.

(We have the CamelWriting option on.)

**Comment by bogenschlag** [comment]
Hi Fabian, can you have a look at this in the coming days? Thanks!

**Comment by fwolf-ilias** [comment]
Hi Christian, I'm sorry for my late reply. My email filter was too rigorous with GitHub mails :(.  I'll have a look on this today.

**Comment by fwolf-ilias** [comment]
Hi Christian, I reorganized the convert functions. In case of "CamelCase" (and in "Lowercased" anyway) the Uppercased umlauts won't be a problem anymore. Sadly the »∂« can't be converted. Maybe changing the locale in "Administration > General Settings" could do the trick.

**Comment by bogenschlag** [comment]
Great, thanks! (»Obscure« characters like ∂ don’t bother me! :)
