### ISSUE TITLE
5.1+?

### ISSUE THREAD

**Issue by bogenschlag** [leifos-gmbh/AutoGenerateUsername#5]
Hallo Fabian,

wie ist denn die weitere Planung bezüglich neuerer ILIAS-Versionen? Will wollen vermutlich nach der DevConf auf 5.1 gehen. Soll die Funktionalität mal in den Core wandern? Oder muss für 5.1-Kompatiblität irgendwas beauftragt werden? (Dann bräuchte ich ASAP ein Angebot … – bzw. abhängig vom Volumen würde ich das dann in unseren Support-Vertrag reinlaufen lassen.)

Danke!

Viele Grüße, Christian

**Comment by bogenschlag** [comment]
Ok, gerade erst den Master-Branch entdeckt – damit hat sich die Frage dann wohl erübrigt …!(?) 😉

**Comment by bogenschlag** [comment]
Ist für 5.1 dann immer noch der Patch nötig? Das scheint es mir nur für 5.0 zu geben hier.

**Comment by fwolf-ilias** [comment]
Ich war noch nicht ganz fertig. Ich hab den Patch für 5.1 hinzugefügt und einen Branch für release_5-1 erstellt. 

Ich werde übrigens den BugTracker von GitHub auf ILIAS Mantis wechseln. Heißt neue Bugs dann lieber in Mantis rein, damit ich den hier schließen kann.

**Comment by bogenschlag** [comment]
Ok, danke, weiß ich Bescheid! 👍🏼

(Schade, ich mag das Issue-Tracking hier eigentlich lieber als Mantis … 😉)
